
trigger:
- main

stages:
- stage: Alpha
  jobs:
  - job: Build
    displayName: 'Build Website'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: PowerShell@2
        displayName: 'Set Build Target'
        inputs:
          targetType: 'inline'
          script: |
            rustup target add wasm32-unknown-unknown
      - task: PowerShell@2
        displayName: 'Run Tests'
        inputs:
          targetType: 'inline'
          script: |
            $test_results = cargo test | Out-String

            if ($test_results.Contains("test result: FAILED")) {
              throw "Tests Failed"
            }
      - task: PowerShell@2
        displayName: 'Set Build Target'
        inputs:
          targetType: 'inline'
          script: |
            # Change directory to webapp
            cd webapp

            # Build
            trunk build
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/webapp/dist'
          ArtifactName: 'drop'
          publishLocation: 'Container'
  - job: Release
    displayName: 'Deploy to Azure'
    dependsOn:
    - Build
    condition: succeeded()
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            Write-Host "Hello World"
