[package]
name = "webui"
version = "0.1.27"
edition = "2021"
description = "`early development` Website UI framework and component library for quickly building websites with native support for Material UI standardization."
keywords = ["webassembly", "ui"]
categories = ["wasm","web-programming"]
license = "MIT"
authors = ["Erik Gasssler"]
documentation = "https://docs.rs/webui"
repository = "https://github.com/StoicDreams/RustWebUI"
homepage = "https://webui.stoicdreams.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
yew-agent = "0.1"
yew-router = "0.16"
gloo-net = "0.2"
gloo-utils = "0.1"
serde = "1.0"
wasm-bindgen-futures = "0.4"
log = "0.4"
console_log = "0.2"
