[package]
name = "webui"
version = "0.3.19"#sync
edition = "2021"
description = "`early development` Website UI framework and component library for quickly building websites with native support for Material UI standardization."
keywords = ["webassembly", "ui"]
categories = ["wasm","web-programming"]
license = "MIT"
authors = ["Erik Gasssler"]
documentation = "https://docs.rs/webui"
repository = "https://github.com/StoicDreams/RustWebUI"
homepage = "https://webui.stoicdreams.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-sys = "0.3"
yew = "0.19"
yew-agent = "0.1"
yew-hooks = "0.1"
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = "1.2"
rust_decimal = "1.26"
rust_decimal_macros = "1.26"
reqwest = "0.11"
regex = "1"
futures = "0.3"
async-std = {version = "1.12", features = ["attributes"] }
