[package]
name = "webui_procs"
version = "0.6.47" #syncwebui
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true
